# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: V:/PL/Soc_Tracking.srcs/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1.xci
# IP: The module: 'Soc_Tracking_AXI4S_fifo_buffer_sl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_638/fifo_generator_638.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_638 || ORIG_REF_NAME==fifo_generator_638} -quiet] -quiet

# IP: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_640/fifo_generator_640.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_640 || ORIG_REF_NAME==fifo_generator_640} -quiet] -quiet

# XDC: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_638/fifo_generator_638.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_638 || ORIG_REF_NAME==fifo_generator_638} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_640/fifo_generator_640.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_640 || ORIG_REF_NAME==fifo_generator_640} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: V:/PL/Soc_Tracking.srcs/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1.xci
# IP: The module: 'Soc_Tracking_AXI4S_fifo_buffer_sl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_638/fifo_generator_638.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_638 || ORIG_REF_NAME==fifo_generator_638} -quiet] -quiet

# IP: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_640/fifo_generator_640.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_640 || ORIG_REF_NAME==fifo_generator_640} -quiet] -quiet

# XDC: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_638/fifo_generator_638.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_638 || ORIG_REF_NAME==fifo_generator_638} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/src/fifo_generator_640/fifo_generator_640.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_640 || ORIG_REF_NAME==fifo_generator_640} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
