# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: V:/src/Cora-Z7-10-Master.xdc

# Block Designs: bd/Soc_Tracking/Soc_Tracking.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking || ORIG_REF_NAME==Soc_Tracking} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_processing_system7_0_0/Soc_Tracking_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_processing_system7_0_0 || ORIG_REF_NAME==Soc_Tracking_processing_system7_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_rst_ps7_0_100M_0/Soc_Tracking_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_rst_ps7_0_100M_0 || ORIG_REF_NAME==Soc_Tracking_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_DMA24bUnit_mm2s_0_1/Soc_Tracking_DMA24bUnit_mm2s_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_DMA24bUnit_mm2s_0_1 || ORIG_REF_NAME==Soc_Tracking_DMA24bUnit_mm2s_0_1} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_zero_padding_0_0/Soc_Tracking_AXI4S_zero_padding_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_zero_padding_0_0 || ORIG_REF_NAME==Soc_Tracking_AXI4S_zero_padding_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_Filter_0_0/Soc_Tracking_AXI4S_Filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_Filter_0_0 || ORIG_REF_NAME==Soc_Tracking_AXI4S_Filter_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_Filter_0_1/Soc_Tracking_AXI4S_Filter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_Filter_0_1 || ORIG_REF_NAME==Soc_Tracking_AXI4S_Filter_0_1} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4_Stream_RGB_to_g_0_0/Soc_Tracking_AXI4_Stream_RGB_to_g_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4_Stream_RGB_to_g_0_0 || ORIG_REF_NAME==Soc_Tracking_AXI4_Stream_RGB_to_g_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_VGA_controller_0_0/Soc_Tracking_VGA_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_VGA_controller_0_0 || ORIG_REF_NAME==Soc_Tracking_VGA_controller_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_Video_TPG_0_0/Soc_Tracking_Video_TPG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_Video_TPG_0_0 || ORIG_REF_NAME==Soc_Tracking_Video_TPG_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_DMA_controller_AXI4L_0_0/Soc_Tracking_DMA_controller_AXI4L_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_DMA_controller_AXI4L_0_0 || ORIG_REF_NAME==Soc_Tracking_DMA_controller_AXI4L_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_Input_selector_AXI4L_0_0/Soc_Tracking_Input_selector_AXI4L_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_Input_selector_AXI4L_0_0 || ORIG_REF_NAME==Soc_Tracking_Input_selector_AXI4L_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_Stream_Duplica_0_0/Soc_Tracking_AXI4S_Stream_Duplica_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_Stream_Duplica_0_0 || ORIG_REF_NAME==Soc_Tracking_AXI4S_Stream_Duplica_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_xbar_1/Soc_Tracking_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_xbar_1 || ORIG_REF_NAME==Soc_Tracking_xbar_1} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_ps7_0_axi_periph_1/Soc_Tracking_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_ps7_0_axi_periph_1 || ORIG_REF_NAME==Soc_Tracking_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_axi_mem_intercon_0/Soc_Tracking_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_axi_mem_intercon_0 || ORIG_REF_NAME==Soc_Tracking_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_Overlay_AXI4L_0_0/Soc_Tracking_AXI4S_Overlay_AXI4L_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_Overlay_AXI4L_0_0 || ORIG_REF_NAME==Soc_Tracking_AXI4S_Overlay_AXI4L_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_0/Soc_Tracking_AXI4S_fifo_buffer_sl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_fifo_buffer_sl_0_0 || ORIG_REF_NAME==Soc_Tracking_AXI4S_fifo_buffer_sl_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1/Soc_Tracking_AXI4S_fifo_buffer_sl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_fifo_buffer_sl_0_1 || ORIG_REF_NAME==Soc_Tracking_AXI4S_fifo_buffer_sl_0_1} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_AXI4S_Binarisation_A_0_0/Soc_Tracking_AXI4S_Binarisation_A_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_AXI4S_Binarisation_A_0_0 || ORIG_REF_NAME==Soc_Tracking_AXI4S_Binarisation_A_0_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_auto_pc_0/Soc_Tracking_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_auto_pc_0 || ORIG_REF_NAME==Soc_Tracking_auto_pc_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_auto_ds_0/Soc_Tracking_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_auto_ds_0 || ORIG_REF_NAME==Soc_Tracking_auto_ds_0} -quiet] -quiet

# IP: bd/Soc_Tracking/ip/Soc_Tracking_auto_pc_1/Soc_Tracking_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Soc_Tracking_auto_pc_1 || ORIG_REF_NAME==Soc_Tracking_auto_pc_1} -quiet] -quiet

# XDC: v:/PL/Soc_Tracking.gen/sources_1/bd/Soc_Tracking/Soc_Tracking_ooc.xdc
